In [1]:
import numpy as np
from tableau_cls import Tableau

In [2]:
# Z eigenstate tableau
# Stabs = +X
# Destabs = +Z

tester = np.array([
[0,1,0],
[1,0,0]
])
tester

array([[0, 1, 0],
       [1, 0, 0]])

In [3]:
tab = Tableau(tester)
tab

Stabilizers: ['+X']
Destabilizers: ['+Z']

In [4]:
tab.H(0)
tab

Stabilizers: ['+Z']
Destabilizers: ['+X']

In [5]:
def print_1q_tab(tableau):
    stabilizer = tab_row_to_str_1q(tableau[0,:])
    destabilizer = tab_row_to_str_1q(tableau[1,:])
    print("Stabilizer:", stabilizer, "Destabilizer:", destabilizer)

In [6]:
def tab_row_to_str_1q(rowvec):
    operator = ''
    operator += 'Z'*rowvec[0] + 'X'*rowvec[1]
    operator = '-' + operator if rowvec[2] else '+' + operator
    return operator

In [7]:
print_1q_tab(tester)

Stabilizer: +X Destabilizer: +Z


In [8]:
tester_2 = np.eye(2000, dtype=int)[0:1999,:]

In [9]:
tester

array([[0, 1, 0],
       [1, 0, 0]])

In [10]:
init_tab = np.eye(5, dtype=int)[0:4,:]

In [31]:
num_qubits = 300
cnot_count = 5
tempvar = 0
init_data = np.eye(2*num_qubits, dtype=int)[0:2*num_qubits-1 ,:]
init_tab = Tableau(init_data)
init_tab.num_qubits

299

In [32]:
randints = [{'control':np.random.randint(num_qubits-1), 'target':np.random.randint(num_qubits-1)} for i in range(cnot_count)]

In [33]:
init_tab.num_qubits

299

In [34]:
%%time
for randint in randints:
    init_tab.CX(**randint)

CPU times: user 2.57 ms, sys: 1.71 ms, total: 4.27 ms
Wall time: 2.68 ms


In [35]:
%%time
for randint in randints:
    init_tab.CX(**randint)

CPU times: user 2.25 ms, sys: 1.54 ms, total: 3.79 ms
Wall time: 2.37 ms


In [36]:
init_tab.data

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0]])

In [58]:
init_tab.CX(0,0)

In [139]:
np.allclose(tempvar,init_tab.data)

True

In [53]:
init_tab.num_qubits

1999

In [54]:
init_tab.H(1550)

In [55]:
init_tab.CZ(2,777)

In [56]:
init_tab.CX(2,222)

In [58]:
init_tab.S(4)

In [59]:
np.asarray?

Docstring:
asarray(a, dtype=None, order=None, *, like=None)

Convert the input to an array.

Parameters
----------
a : array_like
    Input data, in any form that can be converted to an array.  This
    includes lists, lists of tuples, tuples, tuples of tuples, tuples
    of lists and ndarrays.
dtype : data-type, optional
    By default, the data-type is inferred from the input data.
order : {'C', 'F', 'A', 'K'}, optional
    Memory layout.  'A' and 'K' depend on the order of input array a.
    'C' row-major (C-style),
    'F' column-major (Fortran-style) memory representation.
    'A' (any) means 'F' if `a` is Fortran contiguous, 'C' otherwise
    'K' (keep) preserve input order
    Defaults to 'K'.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array 

In [22]:
True * True

1

In [23]:
True ^ True

False

In [25]:
bool(True * False)

False

In [31]:
np.array([True,False]) & np.array([True,True])

array([ True, False])