In [8]:
import numpy as np
from tableaus import *

In [9]:
# Z eigenstate tableau
# Stabs = +X
# Destabs = +Z

tester = np.array([
[0,1,0],
[1,0,0]
])
tester

array([[0, 1, 0],
       [1, 0, 0]])

In [10]:
def print_1q_tab(tableau):
    stabilizer = tab_row_to_str_1q(tableau[0,:])
    destabilizer = tab_row_to_str_1q(tableau[1,:])
    print("Stabilizer:", stabilizer, "Destabilizer:", destabilizer)

In [11]:
def tab_row_to_str_1q(rowvec):
    operator = ''
    operator += 'Z'*rowvec[0] + 'X'*rowvec[1]
    operator = '-' + operator if rowvec[2] else '+' + operator
    return operator

In [12]:
print_1q_tab(tester)

Stabilizer: +X Destabilizer: +Z


In [13]:
print_tab(tester)

Stabilizers: ['+X'] Destabilizers: ['+Z']


In [14]:
tab_row_to_str(tester[0])

'+X'

In [15]:
tester

array([[0, 1, 0],
       [1, 0, 0]])

In [16]:
tester_2 = np.eye(5, dtype=int)[0:4,:]

In [17]:
CNOT(tester_2,0,1)

array([[1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [0, 0, 1, 1, 0],
       [0, 0, 0, 1, 0]])

In [18]:
Phase(np.array([[1, 1, 0],[0, 1, 1]]),0)

array([[0, 1, 1],
       [1, 1, 1]])

In [19]:
tester

array([[0, 1, 0],
       [1, 0, 0]])

In [23]:
init_tab = np.eye(200, dtype=int)[0:199,:]

In [24]:
%%time
for i in range(3000):
    init_tab = CNOT(init_tab,np.random.randint(100),np.random.randint(100))

CPU times: user 110 ms, sys: 9.98 ms, total: 120 ms
Wall time: 115 ms


In [25]:
print_tab(init_tab)

IndexError: index 199 is out of bounds for axis 0 with size 199

In [29]:
len(init_tab[0,:])//2

100

In [30]:
[1,2,3][1:]

[2, 3]