In [28]:
import numpy as np
from tableaus import *
from tableau_cls import Tableau

In [29]:
# Z eigenstate tableau
# Stabs = +X
# Destabs = +Z

tester = np.array([
[0,1,0],
[1,0,0]
])
tester

array([[0, 1, 0],
       [1, 0, 0]])

In [30]:
tab = Tableau(tester)
tab

Stabilizers: ['+X']
Destabilizers: ['+Z']

In [31]:
tab.H(0)
tab

Stabilizers: ['+Z']
Destabilizers: ['+X']

In [32]:
def print_1q_tab(tableau):
    stabilizer = tab_row_to_str_1q(tableau[0,:])
    destabilizer = tab_row_to_str_1q(tableau[1,:])
    print("Stabilizer:", stabilizer, "Destabilizer:", destabilizer)

In [33]:
def tab_row_to_str_1q(rowvec):
    operator = ''
    operator += 'Z'*rowvec[0] + 'X'*rowvec[1]
    operator = '-' + operator if rowvec[2] else '+' + operator
    return operator

In [34]:
print_1q_tab(tester)

Stabilizer: +Z Destabilizer: +X


In [35]:
print_tab(tester)

Stabilizers: ['+Z'] Destabilizers: ['+X']


In [36]:
tab_row_to_str(tester[0])

'+Z'

In [37]:
tester

array([[1, 0, 0],
       [0, 1, 0]])

In [38]:
tester_2 = np.eye(2000, dtype=int)[0:1999,:]

In [39]:
CNOT(tester_2,0,1)

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0]])

In [40]:
Phase(np.array([[1, 1, 0],[0, 1, 1]]),0)

array([[0, 1, 1],
       [1, 1, 1]])

In [41]:
tester

array([[1, 0, 0],
       [0, 1, 0]])

In [42]:
init_tab = np.eye(5, dtype=int)[0:4,:]

In [43]:
%%time
for i in range(3000):
    init_tab = CNOT(init_tab,np.random.randint(100),np.random.randint(100))

IndexError: index 21 is out of bounds for axis 1 with size 5

In [44]:
len(init_tab[0,:])//2

2

In [45]:
[1,2,3][1:]

[2, 3]

In [46]:
vec1 = [1,2,3]
vec2 = [4,5,6]
vec1,vec2 = _swap(vec1,vec2)

NameError: name '_swap' is not defined

In [47]:
vec1

[1, 2, 3]

In [48]:
tab_test = Tableau(init_tab)
tab_test.CX(0,1)
tab_test.data

array([[1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [0, 0, 1, 1, 0],
       [0, 0, 0, 1, 0]])

In [49]:
num_qubits = 2000
cnot_count = 10000
tempvar = 0
init_data = np.eye(2*num_qubits, dtype=int)[0:2*num_qubits-1 ,:]
init_tab = Tableau(init_data)
init_tab.num_qubits

1999

In [50]:
randints = [{'control':np.random.randint(num_qubits), 'target':np.random.randint(num_qubits)} for i in range(cnot_count)]

In [51]:
%%time
for randint in randints:
    init_tab.CX(**randint)

CPU times: user 1.48 s, sys: 61.3 ms, total: 1.55 s
Wall time: 1.55 s


In [52]:
%%time
for randint in randints:
    tempvar = CNOT(init_data,**randint)

CPU times: user 1.53 s, sys: 8.9 ms, total: 1.54 s
Wall time: 1.54 s


In [139]:
np.allclose(tempvar,init_tab.data)

True

In [53]:
init_tab.num_qubits

1999

In [54]:
init_tab.H(1550)

In [55]:
init_tab.CZ(2,777)

In [56]:
init_tab.CX(2,222)

In [58]:
init_tab.S(4)