In [1]:
import numpy as np
from tableaus import *
from tableau_cls import Tableau

In [2]:
# Z eigenstate tableau
# Stabs = +X
# Destabs = +Z

tester = np.array([
[0,1,0],
[1,0,0]
])
tester

array([[0, 1, 0],
       [1, 0, 0]])

In [3]:
tab = Tableau(tester)
tab

Stabilizers: ['+X']
Destabilizers: ['+Z']

In [4]:
tab.H(0)
tab

Stabilizers: ['+Z']
Destabilizers: ['+X']

In [5]:
def print_1q_tab(tableau):
    stabilizer = tab_row_to_str_1q(tableau[0,:])
    destabilizer = tab_row_to_str_1q(tableau[1,:])
    print("Stabilizer:", stabilizer, "Destabilizer:", destabilizer)

In [6]:
def tab_row_to_str_1q(rowvec):
    operator = ''
    operator += 'Z'*rowvec[0] + 'X'*rowvec[1]
    operator = '-' + operator if rowvec[2] else '+' + operator
    return operator

In [7]:
print_1q_tab(tester)

Stabilizer: +Z Destabilizer: +X


In [8]:
print_tab(tester)

Stabilizers: ['+Z'] Destabilizers: ['+X']


In [9]:
tab_row_to_str(tester[0])

'+Z'

In [10]:
tester

array([[1, 0, 0],
       [0, 1, 0]])

In [56]:
tester_2 = np.eye(2000, dtype=int)[0:1999,:]

In [57]:
CNOT(tester_2,0,1)

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0]])

In [13]:
Phase(np.array([[1, 1, 0],[0, 1, 1]]),0)

array([[0, 1, 1],
       [1, 1, 1]])

In [14]:
tester

array([[1, 0, 0],
       [0, 1, 0]])

In [46]:
init_tab = np.eye(5, dtype=int)[0:4,:]

In [23]:
%%time
for i in range(3000):
    init_tab = CNOT(init_tab,np.random.randint(100),np.random.randint(100))

IndexError: index 42 is out of bounds for axis 1 with size 5

In [24]:
len(init_tab[0,:])//2

2

In [25]:
[1,2,3][1:]

[2, 3]

In [26]:
vec1 = [1,2,3]
vec2 = [4,5,6]
vec1,vec2 = _swap(vec1,vec2)

NameError: name '_swap' is not defined

In [27]:
vec1

[1, 2, 3]

In [45]:
tab_test = Tableau(init_tab)
tab_test.CX(0,1)
tab_test.data

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [99]:
num_qubits = 2000
cnot_count = 10000
tempvar = 0
init_data = np.eye(2*num_qubits, dtype=int)[0:2*num_qubits-1 ,:]
init_tab = Tableau(init_data)
init_tab.num_qubits

1999

In [136]:
randints = [{'control':np.random.randint(num_qubits), 'target':np.random.randint(num_qubits)} for i in range(cnot_count)]

In [137]:
%%time
for randint in randints:
    init_tab.CX(**randint)

CPU times: user 1.47 s, sys: 5.18 ms, total: 1.47 s
Wall time: 1.48 s


In [138]:
%%time
for randint in randints:
    tempvar = CNOT(init_data,**randint)

CPU times: user 1.55 s, sys: 2.96 ms, total: 1.55 s
Wall time: 1.55 s


In [139]:
np.allclose(tempvar,init_tab.data)

True